### ISSUE TITLE
I always meeting error as below, so I want know could I install memory-maze not by git command?

### ISSUE THREAD

**Issue by hydro-man** [jurgisp/dmc-memory-maze#1]
`
Collecting dmc-memory-maze
  Cloning https://github.com/jurgisp/dmc-memory-maze.git to c:\users\hnxcd\appdata\local\temp\pip-install-g2hj9ehh\dmc-memory-maze_276fa8f10fe54bec87532cf80ab27f9d
  Running command git clone -q https://github.com/jurgisp/dmc-memory-maze.git 'C:\Users\HNXCD\AppData\Local\Temp\pip-install-g2hj9ehh\dmc-memory-maze_276fa8f10fe54bec87532cf80ab27f9d'
  fatal: unable to access 'https://github.com/jurgisp/dmc-memory-maze.git/': Failed to connect to github.com port 443 after 21056 ms: Timed out
WARNING: Discarding git+https://github.com/jurgisp/dmc-memory-maze.git#egg=dmc-memory-maze. Command errored out with exit status 128: git clone -q https://github.com/jurgisp/dmc-memory-maze.git 'C:\Users\HNXCD\AppData\Local\Temp\pip-install-g2hj9ehh\dmc-memory-maze_276fa8f10fe54bec87532cf80ab27f9d' Check the logs for full command output.
ERROR: Exception:
Traceback (most recent call last):
  File "D:\app\Anaconda\envs\memory_maze\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 341, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "D:\app\Anaconda\envs\memory_maze\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
    raise RequirementsConflicted(criterion)
pip._vendor.resolvelib.resolvers.RequirementsConflicted: Requirements conflict: UnsatisfiableRequirement('dmc-memory-maze')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\app\Anaconda\envs\memory_maze\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    collected.requirements, max_rounds=try_to_avoid_resolution_too_deep
  File "D:\app\Anaconda\envs\memory_maze\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 472, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "D:\app\Anaconda\envs\memory_maze\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 343, in resolve
    raise ResolutionImpossible(e.criterion.information)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=UnsatisfiableRequirement('dmc-memory-maze'), parent=None)]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\app\Anaconda\envs\memory_maze\lib\site-packages\pip\_internal\cli\base_command.py", line 173, in _main
    status = self.run(options, args)
  File "D:\app\Anaconda\envs\memory_maze\lib\site-packages\pip\_internal\cli\req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "D:\app\Anaconda\envs\memory_maze\lib\site-packages\pip\_internal\commands\install.py", line 316, in run
    reqs, check_supported_wheels=not options.target_dir
  File "D:\app\Anaconda\envs\memory_maze\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 101, in resolve
    collected.constraints,
  File "D:\app\Anaconda\envs\memory_maze\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 630, in get_installation_error
    return self._report_single_requirement_conflict(req, parent)
  File "D:\app\Anaconda\envs\memory_maze\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 580, in _report_single_requirement_conflict
    cands = self._finder.find_all_candidates(req.project_name)
  File "D:\app\Anaconda\envs\memory_maze\lib\site-packages\pip\_internal\index\package_finder.py", line 798, in find_all_candidates
    page_candidates = list(page_candidates_it)
  File "D:\app\Anaconda\envs\memory_maze\lib\site-packages\pip\_internal\index\sources.py", line 134, in page_candidates
    yield from self._candidates_from_page(self._link)
  File "D:\app\Anaconda\envs\memory_maze\lib\site-packages\pip\_internal\index\package_finder.py", line 758, in process_project_url
    html_page = self._link_collector.fetch_page(project_url)
  File "D:\app\Anaconda\envs\memory_maze\lib\site-packages\pip\_internal\index\collector.py", line 490, in fetch_page
    return _get_html_page(location, session=self.session)
  File "D:\app\Anaconda\envs\memory_maze\lib\site-packages\pip\_internal\index\collector.py", line 400, in _get_html_page
    resp = _get_html_response(url, session=session)
  File "D:\app\Anaconda\envs\memory_maze\lib\site-packages\pip\_internal\index\collector.py", line 132, in _get_html_response
    "Cache-Control": "max-age=0",
  File "D:\app\Anaconda\envs\memory_maze\lib\site-packages\pip\_vendor\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "D:\app\Anaconda\envs\memory_maze\lib\site-packages\pip\_internal\network\session.py", line 454, in request
    return super().request(method, url, *args, **kwargs)
  File "D:\app\Anaconda\envs\memory_maze\lib\site-packages\pip\_vendor\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\app\Anaconda\envs\memory_maze\lib\site-packages\pip\_vendor\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\app\Anaconda\envs\memory_maze\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 53, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "D:\app\Anaconda\envs\memory_maze\lib\site-packages\pip\_vendor\requests\adapters.py", line 449, in send
    timeout=timeout
  File "D:\app\Anaconda\envs\memory_maze\lib\site-packages\pip\_vendor\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "D:\app\Anaconda\envs\memory_maze\lib\site-packages\pip\_vendor\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "D:\app\Anaconda\envs\memory_maze\lib\site-packages\pip\_vendor\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "D:\app\Anaconda\envs\memory_maze\lib\site-packages\pip\_vendor\urllib3\connection.py", line 506, in _connect_tls_proxy
    ssl_context=ssl_context,
  File "D:\app\Anaconda\envs\memory_maze\lib\site-packages\pip\_vendor\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\app\Anaconda\envs\memory_maze\lib\site-packages\pip\_vendor\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "D:\app\Anaconda\envs\memory_maze\lib\ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "D:\app\Anaconda\envs\memory_maze\lib\ssl.py", line 773, in __init__
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname
`

**Comment by jurgisp** [comment]
There has been some renaming, please try again with the following
```
pip install memory-maze
```
