### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'glGetError'

### ISSUE THREAD

**Issue by mazqtpopx** [jurgisp/dmc-memory-maze#32]
Hi 

I ran a fresh conda env (python 3.9.7), installed `pip install memory-maze` and `pip install gym pygame pillow imageio`. 

When I run `python gui/run_gui.py` I get the following error: 

>python gui/run_gui.py 
Creating environment: memory_maze:MemoryMaze-9x9-v0
Traceback (most recent call last):
  File "/home/leo/memory-maze/gui/run_gui.py", line 231, in <module>
    main()
  File "/home/leo/memory-maze/gui/run_gui.py", line 56, in main
    env = gym.make(args.env, disable_env_checker=True)
  File "/home/leo/miniconda3/envs/memory-maze2/lib/python3.9/site-packages/gym/envs/registration.py", line 540, in make
    importlib.import_module(module)
  File "/home/leo/miniconda3/envs/memory-maze2/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/leo/memory-maze/memory_maze/__init__.py", line 8, in <module>
    from . import tasks
  File "/home/leo/memory-maze/memory_maze/tasks.py", line 2, in <module>
    from dm_control import composer
  File "/home/leo/miniconda3/envs/memory-maze2/lib/python3.9/site-packages/dm_control/composer/__init__.py", line 18, in <module>
    from dm_control.composer.arena import Arena
  File "/home/leo/miniconda3/envs/memory-maze2/lib/python3.9/site-packages/dm_control/composer/arena.py", line 20, in <module>
    from dm_control import mjcf
  File "/home/leo/miniconda3/envs/memory-maze2/lib/python3.9/site-packages/dm_control/mjcf/__init__.py", line 18, in <module>
    from dm_control.mjcf.attribute import Asset
  File "/home/leo/miniconda3/envs/memory-maze2/lib/python3.9/site-packages/dm_control/mjcf/attribute.py", line 28, in <module>
    from dm_control.mujoco.wrapper import util
  File "/home/leo/miniconda3/envs/memory-maze2/lib/python3.9/site-packages/dm_control/mujoco/__init__.py", line 18, in <module>
    from dm_control.mujoco.engine import action_spec
  File "/home/leo/miniconda3/envs/memory-maze2/lib/python3.9/site-packages/dm_control/mujoco/engine.py", line 41, in <module>
    from dm_control import _render
  File "/home/leo/miniconda3/envs/memory-maze2/lib/python3.9/site-packages/dm_control/_render/__init__.py", line 86, in <module>
    Renderer = import_func()
  File "/home/leo/miniconda3/envs/memory-maze2/lib/python3.9/site-packages/dm_control/_render/__init__.py", line 46, in _import_osmesa
    from dm_control._render.pyopengl.osmesa_renderer import OSMesaContext
  File "/home/leo/miniconda3/envs/memory-maze2/lib/python3.9/site-packages/dm_control/_render/pyopengl/osmesa_renderer.py", line 35, in <module>
    from OpenGL import GL
  File "/home/leo/miniconda3/envs/memory-maze2/lib/python3.9/site-packages/OpenGL/GL/__init__.py", line 4, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/home/leo/miniconda3/envs/memory-maze2/lib/python3.9/site-packages/OpenGL/GL/VERSION/GL_1_1.py", line 14, in <module>
    from OpenGL.raw.GL.VERSION.GL_1_1 import *
  File "/home/leo/miniconda3/envs/memory-maze2/lib/python3.9/site-packages/OpenGL/raw/GL/VERSION/GL_1_1.py", line 7, in <module>
    from OpenGL.raw.GL import _errors
  File "/home/leo/miniconda3/envs/memory-maze2/lib/python3.9/site-packages/OpenGL/raw/GL/_errors.py", line 4, in <module>
    _error_checker = _ErrorChecker( _p, _p.GL.glGetError )
AttributeError: 'NoneType' object has no attribute 'glGetError'

Someone else mentioned something about pyopengl in #30, could it be the same issue? 
The versions I have installed are:
memory-maze-1.0.3 
mujoco-3.1.4 
pyopengl-3.1.7

Did I do something wrong/is there something wrong with my environment or is it the pip installation? 

Thanks

**Comment by jurgisp** [comment]
It seems something to do with pyopengl. What is your OS? I have found a similar issue on Ubuntu mentioned here https://github.com/mcfletch/pyopengl/issues/90, see if the fix suggested in the comment there helps?
